import { sections, site, updated } from '../data/content';
import { questions, sources } from '../lib/content';
// llms.txt per https://llmstxt.org/: H1, one-line blockquote summary, short context,
// then H2 sections of "- [name](url): notes" links. Generated from the same data as the
// visible guide so it cannot drift from the page.
const chapters = sections.filter(s => s.id !== 'hero' && s.id !== 'updates');
// First sentence, or as many as it takes to reach ~40 characters so a terse "No." answer still says something.
const firstSentence = (text: string) => { const parts = text.replace(/\s+/g, ' ').trim().split(/(?<=[.!?])\s/); let out = ''; for (const p of parts) { out = out ? `${out} ${p}` : p; if (out.length >= 40) break; } return out; };
const chapterNote = (s: { id: string; markdown: string }) => s.id === 'questions' ? 'Ten plain answers about GEO cost, timelines, guarantees, llms.txt and the training/search split.' : firstSentence(s.markdown.replace(/^###? .*$/gm, '').replace(/\|.*\|/g, ''));
export function GET() {
  const body = `# ${site.name}

> ${site.description}

Published by ${site.publisher.name} (${site.publisher.url}). Contact: ${site.contact}. Last reviewed ${updated}.

GEO (Generative Engine Optimisation) is the practice of improving how visible and accurately represented a website is in answers generated by AI systems such as ChatGPT, Google's AI Overviews and Perplexity. GEO sits on top of SEO rather than replacing it; it influences the odds of being cited and guarantees nothing. This site is a free, single-page educational guide written for business owners and marketers, with no product to sell. This file is a navigation aid, not a statement of ranking eligibility or crawl permission.

## Guide

- [Complete guide, Markdown](${site.url}/guide.md): The whole guide as one Markdown document, with source links.
- [Complete guide, plain text](${site.url}/llms-full.txt): The same guide as plain text.
${chapters.map(s => `- [${s.title}](${site.url}/#${s.id}): ${chapterNote(s)}`).join('\n')}

## Common questions

${questions().map(q => `- [${q.question}](${site.url}/#questions): ${firstSentence(q.answer)}`).join('\n')}

## Sources the guide cites

${sources.map(s => `- [${s.name}](${s.url})`).join('\n')}

## Publisher

- [Adapt Progress Evolve](${site.publisher.url}): The UK software studio that publishes this guide.
- [Adapt Progress Evolve on hilyt](${site.publisher.hilyt}): AI-readable profile of the publisher.
- [What is GEO on hilyt](${site.hilyt}): AI-readable profile of this site.
- [Source code](${site.source}): The site's code on GitHub (MIT); the guide text itself is © the publisher.

## Optional

- [Privacy](${site.url}/privacy/): Newsletter data and website preferences.
- [Sitemap](${site.url}/sitemap.xml)
`;
  return new Response(body, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
}
