import { crawlerSection } from './crawlers';
const baseSections = [
  {
    "title": "Hero",
    "markdown": "Become a source AI can actually cite\n\nGEO helps your business show up accurately when people ask AI tools questions instead of typing them into a search box. This site explains what that means, what actually helps, and what's still guesswork. No hype, no invented stats.\n\n**Understand GEO**",
    "id": "hero"
  },
  {
    "title": "What is GEO?",
    "markdown": "Generative Engine Optimisation (GEO) is the practice of improving how visible and accurately represented your website or content is in answers generated by AI systems like ChatGPT, Google's AI Overviews, or Perplexity. That includes being mentioned, being cited, and sometimes getting a referral click. None of those outcomes are guaranteed. GEO influences the odds; it doesn't fix them.\n\nHere's the thing: GEO isn't a new mystical discipline that replaces everything you already know about being findable online. It's an extension of it. If your site is already thin, unclear, or badly structured, no amount of GEO tinkering will save it. If it's solid, GEO is about making sure AI systems can find, trust, and quote the good parts.\n\nSo this isn't a page selling you a shortcut. It's a page explaining the mechanics, the actual research, and what you can do this month that's worth your time.",
    "id": "what-is-geo"
  },
  {
    "title": "GEO and SEO",
    "markdown": "GEO doesn't replace SEO. It sits on top of it, and overlaps heavily with a related idea called AEO (answer engine optimisation). Same foundation, different output format.\n\n| | SEO | GEO |\n|---|---|---|\n| **Goal** | Rank in search results | Be accurately represented in AI-generated answers |\n| **Format** | Blue links, snippets, rich results | Synthesised answers, sometimes with citations |\n| **Signals** | Crawlability, relevance, authority, technical health | Overlapping content and technical foundations; selection varies by system |\n| **Measurement** | Rankings, impressions, clicks (Search Console) | Manual prompt checks, mentions, citations, referral traffic |\n\nGoogle's own guidance on AI features says existing SEO best practice applies: your page needs to be indexed and eligible for a search snippet to be a supporting link in AI Overviews or AI Mode. That doesn't mean every AI platform uses the same ranking or selection process. There's no special AI schema, no secret file that unlocks inclusion. You can read Google's guide directly at [developers.google.com/search/docs/appearance/ai-features](https://developers.google.com/search/docs/appearance/ai-features).\n\nFair enough, you might think, so why does GEO need its own name at all? Because the selection and synthesis step, how an AI system picks and stitches together passages, behaves differently to how a ranking algorithm sorts ten blue links. That difference is worth understanding on its own terms. That's what the rest of this page is for.",
    "id": "geo-vs-seo"
  },
  {
    "title": "How AI answers happen",
    "markdown": "Not every AI answer involves a live search. Some come straight from what the model learned during training. Training and live retrieval are different things, and it matters which one is happening when you're thinking about visibility.\n\nWhen a system does search the live web to answer you, it roughly follows four stages.\n\n1. **Query.** The system interprets what you're actually asking. It may rewrite your question or split it into several related searches behind the scenes (sometimes called query fan-out), rather than treating it as one single string.\n2. **Discover.** It retrieves a set of candidate sources from the web, using much the same crawling and indexing infrastructure as ordinary search.\n3. **Select.** It chooses specific passages from those candidates, favouring content that answers the question directly and reads as reliable.\n4. **Answer.** It synthesises a response from the selected passages, sometimes showing citations or links back to sources, sometimes not.\n\nThis is a simplified model of a search-backed answer, not a published selection formula. Different systems combine retrieval and generation differently. Updating a page can make new information available to search; it doesn't immediately change a model's training.",
    "id": "how-it-works"
  },
  {
    "title": "The principles",
    "markdown": "### 1. Answer real customer questions, directly\n\nStart with what people genuinely ask, not what you wish they asked. Look at your actual support tickets, sales calls, and reviews for the phrasing customers use. Then answer that question early and plainly, in language a stranger would understand without background context. AI systems are selecting passages that resolve a query cleanly; a page that circles the topic for three paragraphs before answering is a weaker candidate than one that answers in the first two sentences and then elaborates. This isn't about tricking anything. It's about not making the reader, human or machine, hunt for the point.\n\n### 2. Make your content self-contained\n\nA passage pulled out of context still needs to make sense. Avoid answers that depend on \"as mentioned above\" or images with no text equivalent. If a paragraph would be confusing lifted onto someone else's screen with no surrounding page, rewrite it. State who the advice is for, what it assumes, and what it doesn't cover, all inside the same block of text.\n\n### 3. Back claims with real data and explain your method\n\nOriginal data, explained methodology, and specific figures give a page something to cite. Research from Aggarwal et al. (KDD 2024, [arxiv.org/abs/2311.09735](https://arxiv.org/abs/2311.09735)) found that adding citations, quotations, and statistics could improve visibility in benchmark tests, with results varying a lot by domain and topic. That's a research finding under test conditions, not a promise about how any specific production AI system behaves today. Treat it as a reasonable, not guaranteed, lever.\n\n### 4. Show who's behind the words\n\nMake it easy for readers to assess who is responsible for the information. Name a real person or a real organisation. Give them a bio, a role, a reason to be believed. This is a practical credibility recommendation, not proof of a universal AI ranking factor.\n\n### 5. Keep facts current and mark corrections\n\nWhen a fact changes (a price, a regulation, a product spec) update the page and date the change. Don't quietly overwrite; note it. Freshness signals matter more for volatile topics than static ones, so judge accordingly. A page about a fixed historical event doesn't need weekly dating. A page about pricing does.\n\n### 6. Fix the plumbing: structure, crawlability, honesty\n\nClean HTML text, semantic headings, a canonical tag, a working sitemap, accurate structured data. None of this is exotic; it's the same technical hygiene good SEO has asked for for years. What's not on this list: keyword stuffing, fabricated citations, bought reviews, or paying anyone for guaranteed inclusion. Those aren't grey-area tactics. They mislead readers and can breach search platform policies.",
    "id": "principles"
  },
  {
    "title": "A practical example",
    "markdown": "Picture a small furniture shop, sells desks, run by two people and a website. A customer types: \"Will this desk fit a small home office?\"\n\nGeneric marketing copy answers that question badly. \"Our stylish desk brings functionality to any space\" tells the reader nothing they can act on.\n\nHere's a rewrite that does better. *(Illustrative values only, not a real product.)*\n\n> The Elmswood desk measures 120cm wide, 60cm deep, 75cm tall. Measure your available floor space, chair clearance and access before ordering. The top is 120 × 60cm; compare that with your monitor stands and other equipment. Room area alone won't tell you whether it fits.\n\nWhat changed and why: the answer is self-contained (a passage lifted alone still makes sense), it states a limitation honestly instead of hiding it, and it gives numbers a system can quote directly rather than paraphrase vaguely. None of that guarantees an AI system selects or cites this shop over a competitor's page. But it gives the passage a genuine chance of being useful enough to select, which is the only lever available. Use your real specifications and limitations when applying this to your own pages.",
    "id": "example"
  },
  {
    "title": "Your first 30 days",
    "markdown": "A realistic beginner plan. No agency required, no budget assumed.\n\n### Week 1: audit what you already have\n\n- List your top 15 customer questions, pulled from real emails, calls, or reviews.\n- Check whether your existing pages answer any of them directly and self-contained.\n- Check your important pages with URL Inspection in Google Search Console. A `site:yourdomain.com` search is a quick clue, not a complete indexing audit.\n\nWhat to verify: that Google can actually find and index your key pages at all. If it can't, nothing downstream matters yet.\n\n### Week 2: fix the foundations\n\n- Add or tidy semantic headings (H1, H2, H3) on your 5 most important pages.\n- Set canonical tags where duplicate or near-duplicate pages exist.\n- Submit or update your XML sitemap.\n\nWhat to verify: that each key page has one clear H1, a logical heading structure beneath it, and no canonical conflicts confusing search engines about which version is the \"real\" one.\n\n### Week 3: rewrite for direct answers\n\n- Pick your 5 highest-value questions from week 1.\n- Rewrite the top of each relevant page to answer that question in the first two or three sentences.\n- Add author or business identity information where it's missing (an about page, a named contact, a real address).\n\nWhat to verify: read each rewritten answer out loud, alone, with no other page context. Does it still make sense and answer the question fully?\n\n### Week 4: add substance and start watching\n\n- Add one genuinely original piece of data, explanation, or detail per page (a real measurement, a real process, a real limitation), with a note on how you know it.\n- Pick 3 to 5 prompts real customers might type into an AI tool and run them manually.\n- Record what comes back: which platform, which date, what was asked, whether you were mentioned, whether you were cited, and in what context.\n\nWhat to verify: nothing dramatic yet. You're establishing a baseline, not expecting results in week four. That's normal.",
    "id": "getting-started"
  },
  {
    "title": "How to measure progress",
    "markdown": "A vendor's visibility score describes its own sample of prompts and platforms. It isn't a universal GEO rank. Start with a repeatable manual baseline, then judge whether a paid tool measures what you need.\n\n**The core method:** pick a fixed set of prompts that real customers might plausibly ask, and repeat them over time, unchanged. For each one, record:\n\n1. Platform (ChatGPT, Google AI Overview, Perplexity, etc.)\n2. Date\n3. Exact query text used\n4. Whether you were mentioned\n5. Whether you were cited or linked\n6. The surrounding context (were you framed favourably, neutrally, or not at all)\n\nDo this monthly, or after major site changes, using the same prompts each time so you're comparing like with like.\n\nTwo things to keep in mind. First, answers vary. Ask the same question twice and you may get different phrasing, different sources, sometimes a different answer entirely. Some of this is personalisation; the system may weight your location, history, or account differently to someone else's. A single check is a sample, not a universal ranking, and it isn't reproducible for every user everywhere.\n\nSecond, separate this from your existing analytics. Search Console reports search impressions, clicks and position, including Google's AI features within its search reporting. That is different from a complete cross-platform citation audit. Track referral traffic from AI platforms in your analytics tool separately when the referring platform passes that information, and treat actual conversions from that traffic as the metric that matters most. A mention with no click and no action is a nice data point, not a business result.\n\n| What to track | Where | Frequency |\n|---|---|---|\n| Fixed prompt mentions/citations | Manual, across AI platforms | Monthly |\n| Search rankings & impressions | Search Console | Ongoing, as normal |\n| AI referral traffic | Analytics referral reports | Monthly |\n| Referral conversions | Analytics / CRM | Monthly |",
    "id": "measurement"
  },
  {
    "title": "Common questions",
    "markdown": "### What's the actual difference between GEO and SEO?\n\nSEO gets your page ranking in traditional search results. GEO is about being accurately mentioned or cited inside an AI-generated answer. They share the same technical and content foundations; GEO is an additional lens on top, not a separate discipline built from scratch.\n\n### Is SEO dead now that AI answers exist?\n\nNo. Google's own guidance confirms that a page must be indexed and eligible for a normal search snippet before it can feed AI Overviews or AI Mode. SEO is still the foundation everything else stands on. Anyone telling you otherwise is selling something.\n\n### Do I need to write special code for GEO?\n\nNo special schema or dedicated AI text file is required. Clean HTML, semantic headings, working canonical tags, and an accurate sitemap are what actually help, and they're the same things good SEO has always asked for.\n\n### What does GEO cost?\n\nIt depends entirely on what you're starting from. If your content and site structure are already decent, it's mostly time: rewriting for clarity, adding real detail. If you're starting from a broken or thin site, expect more foundational work first. No tool or vendor guarantees results, so spend cautiously and judge by outputs, not promises.\n\n### How long before I see results?\n\nThere's no fixed timeline, and nobody honest will give you one. Give changes at least a few weeks to be recrawled and reconsidered, then check your fixed prompt set monthly. Treat early months as baseline-setting, not results-chasing.\n\n### Do I need an llms.txt file?\n\nIt's an optional, experimental proposal (see [llmstxt.org](https://llmstxt.org/)) for offering AI systems a machine-readable summary of your site. It's not a proven ranking factor, it doesn't grant crawl permission on its own, and it doesn't replace robots.txt or your sitemap. Fine to add once your fundamentals are solid; not urgent.\n\n### Can you guarantee we'll be cited by ChatGPT or Google?\n\nNo, and be wary of anyone who says yes. Citation and mention outcomes vary by platform, query, and time, and no legitimate practice can promise placement in someone else's generated answer.\n\n### What's the difference between AI training and AI search?\n\nTraining is how a model learned language and facts from a large historical dataset, fixed at a point in time. Live retrieval or search is a separate live process where the system fetches and reads current web pages to answer a specific query. Updating your site may affect future retrieval after it is discovered. It doesn't update a trained model immediately; future training decisions are separate.\n\n### Is any of this realistic for a small business with no dedicated marketing team?\n\nYes. Start with a narrow topic where you have real knowledge. Most of the useful work here is writing honestly and clearly about what you actually offer, which any small business owner can do without specialist tools.\n\n### How often should I update GEO-related content?\n\nWhenever a genuine fact changes: prices, specs, availability, regulations. Date the correction. Static, non-volatile pages don't need constant touching just for the sake of activity; that's noise, not signal.",
    "id": "questions"
  },
  {
    "title": "Stay in the loop",
    "markdown": "New guides and course updates land here first, whenever they're ready. No set schedule, no noise, just the useful stuff when it exists.\n\n**Join email updates**",
    "id": "updates"
  }
] as const;
export const supportSections = [
  {
    "title": "Privacy",
    "markdown": "Last updated: 14 September 2026.\n\nHere's the plain version: whatisgeo.app is published by Adapt Progress Evolve. If you've got questions about this notice or want to exercise any of the rights below, email hello@whatisgeo.app or use the contact route on https://adaptprogressevolve.com/.\n\nSignup uses email only. Nothing else is asked for, nothing else is needed.\n\nWe use Resend to send confirmation messages and manage newsletter contacts. When you sign up, you'll get an email asking you to confirm. Until you confirm on the linked page, you're not subscribed. Confirmation links expire after 24 hours. Temporary signup records are automatically scheduled for deletion after that period. Confirmed newsletter contacts remain in Resend until they are no longer needed.\n\nCloudflare hosts and serves this site, and also handles rate limiting to stop abuse. That means your IP address gets seen in the process. The signup service uses it to limit repeated requests. It is not added to your newsletter contact. Cloudflare's own privacy policy covers what it does on its side: https://www.cloudflare.com/privacypolicy/.\n\nConsent for the newsletter is collected at signup, and every message includes an unsubscribe option. Simple as that.\n\nYour browser's localStorage is used for exactly one thing: remembering whether you picked light or dark theme. Nothing tracking-related lives there.\n\nNo advertising tools, no analytics, nothing installed at launch. Fair enough to ask, so we're saying it plainly.\n\nWe keep data only as long as it's needed: to run the subscription, to handle opt-outs or abuse, and to meet any legal obligations that apply.\n\nResend's own privacy policy is here: https://resend.com/legal/privacy-policy.\n\nWant to access, correct, or delete your data, or withdraw consent? Email hello@whatisgeo.app, or contact us through Adapt Progress Evolve's contact route above."
  },
  {
    "title": "Confirmation",
    "markdown": "**Ready**\nClick the button below to finish subscribing. Your subscription starts after you confirm.\n\n**Success**\nYou're confirmed. Future guides and course news will land in your inbox.\n\n**Expired**\nThis link's had its 24 hours. Head back to the homepage and request a fresh one."
  },
  {
    "title": "Not found",
    "markdown": "**Well, this page didn't optimise for anything.**\nThe page you're after isn't here, so let's get you back to something that is. [Back to the guide]"
  }
] as const;
export const ui = {
  "eyebrow": "A field guide to AI search",
  "heroPrimary": "Understand GEO before everyone else pretends to",
  "heroSecondary": "A plain-English starting point for how AI search actually works",
  "signupTitle": "Get the next guide first",
  "signupBody": "New guides and course news, sent when there's something worth sending.",
  "emailLabel": "Email address",
  "emailPlaceholder": "you@example.com",
  "signupButton": "Join email updates",
  "consent": "I'd like email updates about new GEO guides and future courses. I can unsubscribe anytime.",
  "pending": "Check your inbox to confirm.",
  "signupSuccess": "Check your inbox to confirm your email.",
  "signupError": "Something didn't work. Try again in a moment.",
  "unavailable": "Email signup isn't available just yet. Please try again later.",
  "confirmButton": "Confirm my subscription",
  "confirmEmailSubject": "Confirm your subscription to GEO guides",
  "confirmEmailBody": "Click below to confirm you'd like future GEO guides and course news. If you didn't request this, ignore it and nothing happens. This link expires in 24 hours.",
  "confirmEmailButton": "Confirm subscription",
  "footerCredit": "Built by Adapt Progress Evolve",
  "tocTitle": "In this guide",
  "sectionLink": "Jump to section",
  "darkMode": "Dark mode",
  "lightMode": "Light mode",
  "privacyLink": "Privacy",
  "sourcesTitle": "Sources",
  "updatedLabel": "Last updated"
} as const;
export const updated = '14 September 2026';
export const updatedISO = '2026-09-14';
export const publishedISO = '2026-09-14';
export const site = {
  name: 'What is GEO',
  url: 'https://whatisgeo.app',
  description: 'A practical, source-linked guide to Generative Engine Optimisation (GEO) for business owners and marketers.',
  contact: 'hello@whatisgeo.app',
  publisher: { name: 'Adapt Progress Evolve', url: 'https://adaptprogressevolve.com/', hilyt: 'https://i.hilyt.it/ape' },
  hilyt: 'https://i.hilyt.it/whatisgeo'
} as const;
export const sections = [...baseSections.slice(0,5), crawlerSection, ...baseSections.slice(5)];
